### ISSUE TITLE
wrong on build

### ISSUE THREAD

**Issue by GarryLai** [dngulin/ttyhlauncher#38]
./release\util.o:util.cpp:(.text+0x6a7): undefined reference to `_imp___ZN8QuaCrc32C1Ev'
./release\util.o:util.cpp:(.text+0x6bd): undefined reference to `_imp___ZN8QuaCrc329calculateERK10QByteArray'
./release\util.o:util.cpp:(.text+0xbfa): undefined reference to `_imp___ZN6QuaZipC1ERK7QString'
./release\util.o:util.cpp:(.text+0xc15): undefined reference to `_imp___ZN6QuaZip4openENS_4ModeEP19zlib_filefunc_def_s'
./release\util.o:util.cpp:(.text+0xc37): undefined reference to `_imp___ZN10QuaZipFileC1EP6QuaZipP7QObject'
./release\util.o:util.cpp:(.text+0xc43): undefined reference to `_imp___ZN6QuaZip13goToFirstFileEv'
Makefile.Release:213: recipe for target 'release\ttyhlauncher.exe' failed
./release\util.o:util.cpp:(.text+0xef5): undefined reference to `_imp___ZN10QuaZipFile5closeEv'
./release\util.o:util.cpp:(.text+0xf17): undefined reference to `_imp___ZN6QuaZip12goToNextFileEv'
./release\util.o:util.cpp:(.text+0xf2f): undefined reference to `_imp___ZN10QuaZipFile4openE6QFlagsIN9QIODevice12OpenModeFlagEE'
./release\util.o:util.cpp:(.text+0xf40): undefined reference to `_imp___ZNK6QuaZip18getCurrentFileNameEv'
./release\util.o:util.cpp:(.text+0x1215): undefined reference to `_imp___ZN6QuaZip5closeEv'
./release\util.o:util.cpp:(.text+0x121e): undefined reference to `_imp___ZN10QuaZipFileD1Ev'
./release\util.o:util.cpp:(.text+0x1227): undefined reference to `_imp___ZN6QuaZipD1Ev'
./release\util.o:util.cpp:(.text+0x12b8): undefined reference to `_imp___ZN10QuaZipFileD1Ev'
./release\util.o:util.cpp:(.text+0x12c1): undefined reference to `_imp___ZN6QuaZipD1Ev'
E:/Qt/Qt5.5.0/Tools/mingw492_32/bin/../lib/gcc/i686-w64-mingw32/4.9.2/../../../../i686-w64-mingw32/bin/ld.exe: ./release\util.o: bad reloc address 0x13 in section `.eh_frame'
collect2.exe: error: ld returned 1 exit status
mingw32-make[1]: *** [release\ttyhlauncher.exe] Error 1
mingw32-make[1]: Leaving directory 'C:/Users/MonkeyGaga/Desktop/build-ttyhlauncher-Desktop_Qt_5_5_0_MinGW_32bit-Release'
makefile:34: recipe for target 'release' failed
mingw32-make: *** [release] Error 2

please help

**Comment by dngulin** [comment]
Hello, GarryLai!

Can you provide more info about build environment? What version of the libquazip are used and how it installed?

**Comment by GarryLai** [comment]
Oh! I have already fix it
I change tthylauncher.pro line 13
`LIBS += -lquazip5`
to
`LIBS += -Lquazip5 -lquazip`
and I can compete it.
Thanks!

**Comment by GarryLai** [comment]
I want to ask how to use [https://github.com/betrok/minecraft-master](https://github.com/betrok/minecraft-master)
I cant add the account
How to make a register page?
Thanks a lot

**Comment by dngulin** [comment]
Code stored at minecraft-master repository just just implements public client interface. If you want to add new users to database, you need to implement this function in sign-in page or insert users manually.

Look at player-table structure in https://github.com/betrok/minecraft-master/blob/master/schema.sql#L64 for details about record columns.

You also need to look at m_login function in https://github.com/betrok/minecraft-master/blob/master/functions.php to understand how player password stored.
