### ISSUE TITLE
Can't login server

### ISSUE THREAD

**Issue by GarryLai** [dngulin/ttyhlauncher#39]
I success login on launcher
But when I enter minecraft server
`Authentication servers are down. Please try again later, sorry!`
Is it a SSL problem??
(my authlib had already change URL)
Please help
Thanks a lot

**Comment by dngulin** [comment]
Hello, GarryLai!

You also need to integrate server and authentication server (change url in server jar).
Additionally you need to set own session server certificate (der file) in server jar.
